name: Setup node

on: [push]

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [6, 8, 14]
        os: ['macos_latest', 'ubuntu-latest', 'windows-latest']
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: log default node-version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: log node-version
        run: node -v